### ISSUE TITLE
Post Entry Validation

### ISSUE THREAD

**Issue by peterpasz** [peterpasz/ShareScape#11]
If we decide to leave the manual link entry in addition to the imgur generation, we may have to add some validation to make sure the link ends jpg, png, etc.

**Comment by AlexZadorojnyi** [comment]
I think it's probably best to leave out the manual link entry for the final version.

**Comment by peterpasz** [comment]
Ya, I'm thinking the same thing. For the time being, I made it so that the input field gets disabled while an image is being uploaded to imgur.

**Comment by AlexZadorojnyi** [comment]
I added a link validation function that verifies that the link ends with either .jpg, .png, or .gif.
