### ISSUE TITLE
Map Features

### ISSUE THREAD

**Issue by peterpasz** [peterpasz/ShareScape#5]
Have map actively show user's location (Google GPS?)
Send user's coordinates into pos:[lat,lon] any time user uploads
Somehow display markers using database of posts

**Comment by AlexZadorojnyi** [comment]
@peterpasz Could you look into if there is a problem with the coordinates on the database end? Even when I hard-coded `pos: { lat: 1, lon: 2 }` into createPost it wouldn't show up under the post object in the web console.

**Comment by peterpasz** [comment]
@AlexZadorojnyi Wana commit the changes you tried making as a comment? I'll take a look at how you're trying to do hard code it.

**Comment by peterpasz** [comment]
@AlexZadorojnyi  Okay, it seems to be working now. Location should automatically add itself to posts. Try pulling the change and see if it works for you.

**Comment by peterpasz** [comment]
Almost done. Need map to auto-follow user as they move, and this issue should be good.

**Comment by peterpasz** [comment]
Mostly done, adding remaining features to new task in Sprint C.
